services:
  postgres:
    image: postgres:16-alpine
    container_name: maridimamba-postgres
    environment:
      POSTGRES_DB: maridimamba
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
