-- V1__init_schema.sql
-- Village Group Money Management Database Schema

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    role VARCHAR(30) NOT NULL, -- LEADER, MEMBER, ADMIN
    phone VARCHAR(20),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    address VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE monthly_cycles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_name VARCHAR(50) NOT NULL, -- e.g. "September 2026"
    month_date DATE NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    opening_balance DECIMAL(15, 2) NOT NULL,
    lending_amount DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    reserve_amount DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    chunk_amount DECIMAL(15, 2) NOT NULL DEFAULT 5000.00,
    number_of_chunks INT NOT NULL DEFAULT 0,
    closing_balance DECIMAL(15, 2),
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN', -- OPEN, CLOSED
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP
);

CREATE TABLE loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id BIGINT NOT NULL REFERENCES monthly_cycles(id),
    member_id BIGINT NOT NULL REFERENCES members(id),
    chunk_number INT NOT NULL,
    principal_amount DECIMAL(15, 2) NOT NULL,
    interest_amount DECIMAL(15, 2) NOT NULL,
    total_due DECIMAL(15, 2) NOT NULL,
    amount_paid DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    remaining_amount DECIMAL(15, 2) NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING', -- PENDING, PARTIALLY_PAID, PAID, OVERDUE
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id BIGINT NOT NULL REFERENCES loans(id),
    member_id BIGINT NOT NULL REFERENCES members(id),
    cycle_id BIGINT NOT NULL REFERENCES monthly_cycles(id),
    amount DECIMAL(15, 2) NOT NULL,
    principal_portion DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    interest_portion DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    payment_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    recorded_by VARCHAR(50) NOT NULL,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ledger_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id BIGINT REFERENCES monthly_cycles(id),
    transaction_type VARCHAR(30) NOT NULL, -- OPENING_BALANCE, LOAN_DISBURSEMENT, LOAN_REPAYMENT, OTHER_INCOME, OTHER_EXPENSE
    amount DECIMAL(15, 2) NOT NULL, -- Positive for money in, negative for money out
    running_balance DECIMAL(15, 2) NOT NULL,
    reference_type VARCHAR(30), -- CYCLE, LOAN, PAYMENT, MANUAL
    reference_id BIGINT,
    description TEXT NOT NULL,
    transaction_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    action VARCHAR(50) NOT NULL,
    entity_type VARCHAR(50) NOT NULL,
    entity_id VARCHAR(50),
    old_value TEXT,
    new_value TEXT,
    ip_address VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for optimal lookup and reporting performance
CREATE INDEX idx_members_active ON members(active);
CREATE INDEX idx_cycles_status ON monthly_cycles(status);
CREATE INDEX idx_loans_cycle ON loans(cycle_id);
CREATE INDEX idx_loans_member ON loans(member_id);
CREATE INDEX idx_loans_status ON loans(status);
CREATE INDEX idx_payments_loan ON payments(loan_id);
CREATE INDEX idx_payments_member ON payments(member_id);
CREATE INDEX idx_payments_cycle ON payments(cycle_id);
CREATE INDEX idx_ledger_cycle ON ledger_transactions(cycle_id);
CREATE INDEX idx_ledger_type ON ledger_transactions(transaction_type);
CREATE INDEX idx_ledger_date ON ledger_transactions(transaction_date);
